import Queue from 'bull';

const queueComment = new Queue('queueHashtagCrawlApi','redis://127.0.0.1:6379')

const urlVdideo = [

  "#VinaCapital",
  "#VCFM",
  "#abetterlifeathome",
  "#bhsgroup",
  "#bimland",
  "#buucucGHN",
  "#ChipContactless",
  "#comehomescvivocity",
  "#comehomevietnam",
  "#GHN",
  "#ghnexpress",
  "#GHNHCM",
  "#ghnhn",
  "#giaohangnhanh",
  "#goldengate",
  "#kichikichi",
  "#laithuskoda",
  "#LifeWear",
  "#londonex",
  "#MadamNu",
  "#NAPAS",
  "#NAPAS247",
  "#PNJ",
  "#Shinhanfiance",
  "#Skoda",
  "#skodavietnam",
  "#Superb_2024",
  "#tamsugiaohangcungghn",
  "#tapchitrading",
  "#taychayghn",
  "#taychaygiaohangnhanh",
  "#thunglungthanhxuan",
  "#UNIQLOHanoi",
  "#UNIQLOHCMC",
  "#UNIQLOVN",
  "#VietQR",
  "#kinhmatanna",
  "#FWDBảohiểmdễhiểu",
  "#FWDSốngđầytừhômnay",
  "#FWDSớmbảovệ",
  "#FWDBaohiemdehieu",
  "#FWDSốngdầytừhômnay",
  "#FWDSombaove",
  "#FWDCelebrateLivingStory",
  "#FWDTimetoPlay",
  "#FWDAgencyKickoff2024",
  "#TrailblazerAwards2024",
  "#FWD",
  "#EQuest",
  "#A_member_of_EQuest_Education",
  "#Accredited",
  "#BeFinancial",
  "#Cognia",
  "#DogiaCapital",
  "#DSH",
  "#duan10B",
  "#Dwight",
  "#dwightschool",
  "#dwightschoolhanoi",
  "#DwightSchoolHanoiSparkOfGenius",
  "#EQuest_Education",
  "#EQuest_Education_Group",
  "#EQuest_Group",
  "#LanvinhHaLong",
  "#vanphuinvest",
  "#TheNextKOC",
  "#aptamil",
  "#kbsv_cltt_2024",
  "#kbsv",
  "#chungkhoankbsv",
  "#KBSecurities",
  "#KB_Securities",
  "#KBVietnam",
  "#KBBuddy",
  "#KB_Buddy",
  "#KBMobile",
  "#KB_Mobile",
  "#KBMobileDS",
  "#KB_MobileDS",
  "#KBTrade",
  "#KB_Trade",
  "#KBable",
  "#Kb_able",
  "#KBTradeDS",
  "#KB_TradeDS",
  "#KBQuote",
  "#Kb_Quote",
  "#KBOpen",
  "#KB_Open",
///////////////////////
// "#1212SANG0D",
//   "#1212TOI0D",
//   "#1212TRUA0D",
//   "#12SIEUSHIP",
//   "#AnCungTikTok",
//   "#AOKHOACGIOYODY",
//   "#appFuta",
//   "#BAO50",
//   "#baobimoi",
//   "#Bésiêunhân",
//   "#boovietnam",
//   "#Cănhộdulịchbiển5saoVũngTàu",
//   "#Canifa",
//   "#caodangcntt",
//   "#CaoDangNova",
//   "#CaodangVietMy",
//   "#Chienbinhtantam",
//   "#Chuyenxehuongnghiep_ITC2023",
//   "#CollabCollection2023",
//   "#ColosDHA",
//   "#coolmate",
//   "#Cuoianhdi",
//   "#DAITIEC12",
//   "#daitiecgiaxinh",
//   "#DCApp",
//   "#DCFund",
//   "#DCVFM",
//   "#đènledvianco",
//   "#dienquang",
//   "#doibong_sangden",
//   "#doibongsangden",
//   "#DragonCapital",
//   "#DragonX",
//   "#Elise",
//   "#enfa",
//   "#FamiCanxi",
//   "#G-smile",
//   "#ghn",
//   "#GHN_phốt",
//   "#GHN10nam",
//   "#ghnancap",
//   "#ghnlàmănthiếutráchnhiệm",
//   "#GHNlamhuhonghang",
//   "#ghnlừađảo",
//   "#ghnrutruot",
//   "#ghntraohang",
//   "#ghnvotrachnhiem",
//   "#Giao_hàng_nhanh_gian_lận",
//   "#giaohangnhanhantrom",
//   "#giaohangnhanhgianlan",
//   "#Gojek8K",
//   "#Gsmile",
//   "#hanhtrinhthanhxuancungshopeefood",
//   "#HePhongThu1170",
//   "#HMVietnam",
//   "#hoangphucinternational",
//   "#Hunglocvivang",
//   "#IntoYourself",
//   "#itstartsonTikTok",
//   "#ivymoda",
//   "#laithuskoda",
//   "#learnontiktok",
//   "#londonex",
//   "#lookgoodfeelgood",
//   "#macroequities",
//   "#MangoVN",
//   "#Mẹsiêuphàm",
//   "#Milovietnam",
//   "#MORNING12",
//   "#moshopeedungshopeepay",
//   "#MuaDealYeuThuong",
//   "#MuonShopeeFoodToTinh",
//   "#NANOptipro4",
//   "#nemfahsion",
//   "#neotrades",
//   "#NhungDoaHoaKienCuong",
//   "#Ninomaxx",
//   "#Ninomaxx_Concept",
//   "#NovaCollege",
//   "#NowdoitenthanhShopeeFood",
//   "#NowShopeeFood1808",
//   "#phốtghn",
//   "#PolyKBeauty",
//   "#rangdong",
//   "#SHEINVN",
//   "#ShopeeFood1010",
//   "#ShopeeFood1111",
//   "#ShopeeFood1212",
//   "#ShopeeFood1402",
//   "#ShopeeFood1501",
//   "#ShopeeFood99",
//   "#SIEUDEAL",
//   "#SIEUSALE",
//   "#SIEUTIEC0D",
//   "#Skoda",
//   "#skodavietnam",
//   "#SOHO",
//   "#SPFOOD122",
//   "#SPFOOD5",
//   "#SPFOOD82",
//   "#SữaĐặcÔngThọ",
//   "#TaiKhoanTichLuy",
//   "#TaiKhoanTraSau",
//   "#Tantam100",
//   "#TantamviShop",
//   "#Tantaytantam",
//   "#TậpđoànBĐSAnGia",
//   "#TetNgonHuHon",
//   "#thunglungthanhxuan",
//   "#tiktoklivevietnam",
//   "#TikTokVietnam",
//   "#tiktokvn",
//   "#TLC",
//   "#TommyJeansVN",
//   "#topmanVN",
//   "#Trieudondonghanh",
//   "#trợgiúpgiảiđápkhiếunại",
//   "#tuithantai",
//   "#vanlangsaigon",
//   "#vianco",
//   "#viancolighting",
//   "#Vivang",
//   "#Vivangtrolai",
//   "#vivangzalopay",
//   "#vuatuoivuamoi",
//   "#wolfooincanifa",
//   "#xekhachphuongtrang",
//   "#Xephuongtrang",
//   "#XinchaoShopeeFood",
//   "#yesmom",
//   "#Yeuminhdungdeminhdoi",
//   "#yody",
//   "#YODYJEAN",
//   "#YODYOFFICE",
//   "#YODYxMYTAM",
//   "#YODYYEU",
//   "#FWDBảohiểmdễhiểu",
//   "#FWDSốngđầytừhômnay",
//   "#FWDSớmbảovệ",
//   "#FWDBaohiemdehieu",
//   "#FWDSốngdầytừhômnay",
//   "#FWDSombaove",
//   "#FWDCelebrateLivingStory",
//   "#FWDTimetoPlay",
//   "#FWDAgencyKickoff2024",
//   "#TrailblazerAwards2024",
//   "#FWD",
//   "#Mình_luôn_cần_nhau",
//   "#Prudential",
//   "#Tết_chỉ_cần_có_nhau",
//   "#Người_Lạ_Tôi_Cần",
//   "#ManulifeVietNam",
//   "#ActsofKindness",
//   "#quymomanulife",
//   "#AIA",
//   "#NestbyAIA",
//   "#AIAExchange",
//   "#AIAVietnam",
//   "#AIAVitality",
//   "#exchangebyaia",
//   "#tuhaohanhtrinhtoichon",
//   "#DaiichiLife",
//   "#DaiichiLifeVietnam",
//   "#Hiểuđúngbảovệđủ",
//   "#DaiichiConnect",
//   "#GeneraliVietnam",
//   "#SốngNhưÝ",
//   "#SunLifeVietnam",
//   "#LifeIsBrighterUnderTheSun",
//   "#KeHoachLacQuan",
//   "#SUNvungvang",
//   "#agencynextmove",
//   "#Ganbodailau",
]

for(let i=0;i<urlVdideo.length;i++){
    queueComment.add({hashtag:`${urlVdideo[i]}`})
    console.log({hashtag:`${urlVdideo[i]}`})
}

// await queueComment.obliterate({ force: true });
// const a = await queueComment.count()
// console.log(a)
